project:
  type: website
  
website:
  title: "E-PORTFOLIO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: "#F5F5F5"

format:
  html:
    theme:
      - lumen
      - styles.css
    toc: true
    toc-location: left



